### ISSUE TITLE
Change the title of the readme to match the title of the repository

### ISSUE THREAD

**Issue by rebekah-zhou** [learn-co-curriculum/phase-0-the-dom-modifying-elements-lab#8]
### Canvas Link

https://learning.flatironschool.com/courses/5055/assignments/152488?module_item_id=324578

### Concern

It would be nice to have the title of the readme match the title of the repository.

**Comment by ihollander** [comment]
Hi @rebekah-zhou - thanks for your suggestion! Since we have internal documentation that refers to the names of lessons in many places, unfortunately it's not simple for us to change the title in a Readme without updating the same information in many places. Since in this case the title is an accurate description of the contents of the lesson, we're going to leave it as is.
